## H2 Database
spring:
  flyway.enabled: false
  h2.console:
    enabled: true
    path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

project:
  mail:
    host: smtp.gmail.com
    port: 587
    username: mailer@example.com
    password: example
    tls: true
    ssl: false
